substitutions:
  plug_name: mhz19

esphome:
  name: mhz19
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "fiwissid"
  password: "assword"

 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mhz19 Fallback Hotspot"
    password: "password"

web_server:
  port: 80     

captive_portal:

# Enable logging
#logger:

# Enable Home Assistant API
api:
  password: "assword"

ota:
  safe_mode: True
  password: "assword"
  
# Example configuration entry
uart:
  rx_pin: D5
  tx_pin: D6
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    
#sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "DHT-22 Temperature"
    humidity:
      name: "DHT-22 Humidity"
    update_interval: 60s



# Example configuration entry
#sensor:
  - platform: uptime
    name: ${plug_name}_uptime

  - platform: wifi_signal
    name: ${plug_name}_wifi_signal
    update_interval: 60s

text_sensor:
  - platform: version
    name: ${plug_name}_firmware_version
    
